package model;

import java.io.Serializable;
import javax.persistence.*;
import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * The persistent class for the opt_out database table.
 * 
 */
@Entity
@Table(name="opt_out")
@NamedQuery(name="OptOut.findAll", query="SELECT o FROM OptOut o")
public class OptOut implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	private long id;

	@Column(name="auto_generated")
	private BigDecimal autoGenerated;

	@Column(name="date_created")
	private Timestamp dateCreated;

	@Column(name="email_address")
	private String emailAddress;

	@Column(name="organization_id")
	private BigDecimal organizationId;

	public OptOut() {
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public BigDecimal getAutoGenerated() {
		return this.autoGenerated;
	}

	public void setAutoGenerated(BigDecimal autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

	public Timestamp getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Timestamp dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public BigDecimal getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(BigDecimal organizationId) {
		this.organizationId = organizationId;
	}

}